/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_adoptopenjdk_integration_ClassWithNativeCall */

#ifndef _Included_net_adoptopenjdk_integration_ClassWithNativeCall
#define _Included_net_adoptopenjdk_integration_ClassWithNativeCall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_adoptopenjdk_integration_ClassWithNativeCall
 * Method:    callNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_adoptopenjdk_integration_ClassWithNativeCall_callNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
