.TH itweb-settings 1 "07 Mar 2014"

.SH NAME

itweb-settings - view and modify settings for
.B
javaws
and the browser plugin

.SH SYNOPSIS

.B itweb-settings
.br
.B itweb-settings
command arguments
.SH DESCRIPTION
.B itweb-settings
is a command line and a GUI program to modify and edit settings used by the
icedtea-web implementation of
.B javaws
and the browser plugin.

If executed without any arguments, it starts up a GUI. Otherwise, it tries to
do what is specified in the argument.

The command-line allows quickly searching, making a copy of and modifying
specific settings without having to hunt through a UI.


.SH COMMANDS

.TP
help
Prints out information about supported command, descriptions and basic usage.
.TP 12
list
Shows a list of all settings.
.TP
get <name>
Shows the value of the named setting.
.TP
info <name>
Shows additional information about the named setting. Includes a description,
the current value, the possible values, and the source of the setting.
.TP
set <name> <value>
Sets the setting to the new value, after checking that it is an appropriate
value.
.TP
reset all
Resets all settings to their original values.
.TP
reset <name>
Resets the named setting to its original value.
.TP
check <name>
Checks that the current value of the setting is a valid value.

.SH EXAMPLES

.TP
itweb-settings

Show the GUI editor

.TP
itweb-settings reset deployment.proxy.type

Resets the value of 'deployment.proxy.type' setting.


.SH FILES

$XDG_CONFIG_HOME/icedtea-web/deployment.properties specifies the settings used

.SH BUGS

There arent any known bugs. If you come across one, please file it at
    http://icedtea.classpath.org/bugzilla/

.SH AUTHOR

Written and maintained by the IcedTea contributors.

.SH SEE ALSO

.BR javaws (1),
.BR java (1)
.br
http://icedtea.classpath.org/wiki/IcedTea-Web
