.TH javaws 1 "9 Sep 2010"
.SH NAME
javaws - a Java Web Start client
.SH SYNOPSYS
.B javaws
[-run-options] jnlp-file
.br
.B javaws
[-control-option]
.SH DESCRIPTION
.B javaws
is an implementation of a JNLP  client. It uses a JNLP (Java Network
Launch Protocol) file to securely run a remote Java application or
a Java applet.  This implementation of
.B javaws
is from the IcedTea project and is based on the NetX project.
.PP
A JNLP file is an xml file that describes how to securely run a
remote Java application or a Java applet.

.SH OPTIONS
When specifying options, the name of the jnlp file must be the last
argument to
.B javaws
- all the options must preceede it.
.PP
The jnlp-file can either be a url or a local path.
.PP
.B Control Options
.PP
By default
.B javaws
will launch the jnlp file specified on the command line. The control
options can be used to change this behaviour.
.TP 12
\-about
Shows a sample application that can be used to test the basic functionality
of this implementation.
.TP
\-viewer
Shows the trusted certificate viewer. This allows a user to list, examine, remove
or export trusted certificates. Note that this only reflects the certificates
trusted by
.B javaws
and not any other certificates or programs.

.PP
.B Run Options
.PP
In the default mode, the following run-options can be used:
.TP 12
\-basedir dir
Directory where the cache and certificates to be used are stored.
.TP
\-arg arg
Adds an application argument before launching.
.TP
\-param name=value
Adds an applet parameter before launching.
.TP
\-property name=value
Sets a system property before launching.
.TP
\-update seconds
Update check if seconds since last checked.
.TP
\-license
Display the GPL license and exit.
.TP
\-verbose
Enable verbose output. Very useful in debugging.
.TP
\-nosecurity
Disables the secure runtime environment.
.TP
\-noupdate
Disables checking for updates.
.TP
\-headless
Disables download window, other UIs.
.TP
\-strict
Enables strict checking of JNLP file format. Any deviations from
the JNLP DTD will cause
.B javaws
to abort.
.TP
\-umask=value
Sets the umask for files created by an application.
.TP
\-Xnofork
Do not create another JVM, even if the JNLP file asks for running in
a separate JVM. This is useful for debugging.
.TP
\-Jjava-option
This passes along java-option to the java binary that is running
javaws. For example, to make javaws run with a max heap size
of 80m, use -J-Xmx80m.
.TP
\-help
Print a help message and exit.

.SH FILES
~/.icedtea/deployment.properties specifies the settings used by javaws

.SH BUGS
There arent any known bugs. If you come across one, please file it at
    http://icedtea.classpath.org/bugzilla/
.br
Please run javaws in verbose mode and include that output along
with the jnlp file when filing out the bug report.

.SH AUTHOR
Originally written by Jon. A. Maxwell.
.br
Currently maintained by the IcedTea contributors.

.SH SEE ALSO
.BR java (1)
.br
http://icedtea.classpath.org/
.br
http://jnlp.sourceforge.net/netx/
